add files for QuickStart tutorial
su2code/Tutorials pull request #43
Opened 2023-07-02 16:46 UTC by frx-wintermute

This pull request is part of plan (B) described in https://github.com/su2code/su2code.github.io/pull/134#issuecomment-1616012091

2023-07-15 21:21 UTC, pcarruscag approved these changes

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/adj/inv_adj_NACA0012.cfg
> +RESTART_SOL= NO
```suggestion
SOLVER= EULER
MATH_PROBLEM= CONTINUOUS_ADJOINT
RESTART_SOL= NO
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/adj/inv_adj_NACA0012.cfg
> +FREESTREAM_TEMPERATURE= 273.15
```suggestion
MACH_NUMBER= 0.8
AOA= 1.25
FREESTREAM_PRESSURE= 101325.0
FREESTREAM_TEMPERATURE= 273.15
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/adj/inv_adj_NACA0012.cfg
> +REF_DIMENSIONALIZATION= DIMENSIONAL
```suggestion
GAMMA_VALUE= 1.4
GAS_CONSTANT= 287.87

% ---------------------- REFERENCE VALUE DEFINITION ---------------------------%

REF_ORIGIN_MOMENT_X = 0.25
REF_ORIGIN_MOMENT_Y = 0.00
REF_ORIGIN_MOMENT_Z = 0.00
REF_LENGTH= 1.0
REF_AREA= 1.0
REF_DIMENSIONALIZATION= DIMENSIONAL
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/adj/inv_adj_NACA0012.cfg
> +MARKER_DESIGNING = ( airfoil )
```suggestion
MARKER_EULER= ( airfoil )
MARKER_FAR= ( farfield )

% ------------------------ SURFACES IDENTIFICATION ----------------------------%

MARKER_PLOTTING = ( airfoil )
MARKER_MONITORING = ( airfoil )
MARKER_DESIGNING = ( airfoil )
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/adj/inv_adj_NACA0012.cfg
> +CFL_ADAPT_PARAM= ( 0.1, 2.0, 10.0, 1e10 )
```suggestion
NUM_METHOD_GRAD= WEIGHTED_LEAST_SQUARES
OBJECTIVE_FUNCTION= DRAG
CFL_NUMBER= 1e3
CFL_ADAPT= NO
CFL_ADAPT_PARAM= ( 0.1, 2.0, 10.0, 1e10 )
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/adj/inv_adj_NACA0012.cfg
> +LINEAR_SOLVER_ITER= 10
```suggestion
LINEAR_SOLVER= FGMRES
LINEAR_SOLVER_PREC= ILU
LINEAR_SOLVER_ERROR= 1E-10
LINEAR_SOLVER_ITER= 10
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/adj/inv_adj_NACA0012.cfg
> +MG_DAMP_PROLONGATION= 1.0
```suggestion
MGLEVEL= 3
MGCYCLE= W_CYCLE
MG_PRE_SMOOTH= ( 1, 2, 3, 3 )
MG_POST_SMOOTH= ( 0, 0, 0, 0 )
MG_CORRECTION_SMOOTH= ( 0, 0, 0, 0 )
MG_DAMP_RESTRICTION= 1.0
MG_DAMP_PROLONGATION= 1.0
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/adj/inv_adj_NACA0012.cfg
> +% Time discretization (RUNGE-KUTTA_EXPLICIT, EULER_IMPLICIT, EULER_EXPLICIT)
```suggestion
CONV_NUM_METHOD_FLOW= JST
JST_SENSOR_COEFF= ( 0.5, 0.02 )
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/adj/inv_adj_NACA0012.cfg
> +% Time discretization (RUNGE-KUTTA_EXPLICIT, EULER_IMPLICIT)
```suggestion
CONV_NUM_METHOD_ADJFLOW= JST
CFL_REDUCTION_ADJFLOW= 0.01
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/dadj/inv_dadj_NACA0012.cfg
> +RESTART_SOL= NO
```suggestion
SOLVER= EULER
MATH_PROBLEM= DISCRETE_ADJOINT
RESTART_SOL= NO
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/dadj/inv_dadj_NACA0012.cfg
> +FREESTREAM_TEMPERATURE= 273.15
```suggestion
MACH_NUMBER= 0.8
AOA= 1.25
FREESTREAM_PRESSURE= 101325.0
FREESTREAM_TEMPERATURE= 273.15
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/dadj/inv_dadj_NACA0012.cfg
> +% Specific gas constant (287.87 J/kg*K (air), only for compressible flows)
```suggestion
GAMMA_VALUE= 1.4
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/dadj/inv_dadj_NACA0012.cfg
> +%                              FREESTREAM_VEL_EQ_MACH, FREESTREAM_VEL_EQ_ONE)
```suggestion
REF_ORIGIN_MOMENT_X = 0.25
REF_ORIGIN_MOMENT_Y = 0.00
REF_ORIGIN_MOMENT_Z = 0.00
REF_LENGTH= 1.0
REF_AREA= 1.0
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/dadj/inv_dadj_NACA0012.cfg
> +% Marker of the far field (NONE = no marker)
```suggestion
MARKER_EULER= ( airfoil )
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/dadj/inv_dadj_NACA0012.cfg
> +% Marker(s) of the surface where obj. func. (design problem) will be evaluated
```suggestion
MARKER_PLOTTING = ( airfoil )
MARKER_MONITORING = ( airfoil )
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/dadj/inv_dadj_NACA0012.cfg
> +% Number of total iterations
```suggestion
NUM_METHOD_GRAD= WEIGHTED_LEAST_SQUARES
OBJECTIVE_FUNCTION= DRAG
CFL_NUMBER= 1e3
CFL_ADAPT= NO
CFL_ADAPT_PARAM= ( 0.1, 2.0, 10.0, 1e10 )
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/dadj/inv_dadj_NACA0012.cfg
> +% Max number of iterations of the linear solver for the implicit formulation
```suggestion
LINEAR_SOLVER= FGMRES
LINEAR_SOLVER_PREC= ILU
LINEAR_SOLVER_ERROR= 1E-10
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/dadj/inv_dadj_NACA0012.cfg
> +% Damping factor for the correction prolongation
```suggestion
MGLEVEL= 3
MGCYCLE= W_CYCLE
MG_PRE_SMOOTH= ( 1, 2, 3, 3 )
MG_POST_SMOOTH= ( 0, 0, 0, 0 )
MG_CORRECTION_SMOOTH= ( 0, 0, 0, 0 )
MG_DAMP_RESTRICTION= 1.0
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/dadj/inv_dadj_NACA0012.cfg
> +TIME_DISCRE_FLOW= EULER_IMPLICIT
```suggestion
CONV_NUM_METHOD_FLOW= JST
JST_SENSOR_COEFF= ( 0.5, 0.02 )
TIME_DISCRE_FLOW= EULER_IMPLICIT
```

2023-07-15 21:21 UTC, pcarruscag commented on compressible_flow/QuickStart/dadj/inv_dadj_NACA0012.cfg
> +
```suggestion
```

2023-07-15 21:32 UTC, pcarruscag requested changes
I think you opened the PR but did not allow commits from maintainers, you'll have to apply the suggestions above yourself unfortunately.

2023-07-16 17:01 UTC, frx-wintermute commented
> I think you opened the PR but did not allow commits from maintainers, you'll have to apply the suggestions above yourself unfortunately.

Yes, I confirm that I opened the pull request without allowing commits from maintainers: the rationale is that I would like to understand and check any change you possibly ask me to apply, as in this very case.

If I am not mistaken, you are asking me to strip out all the comments from the two configuration files. Why so?

Other tutorials seem to have configuration files with comments. For instance: https://github.com/su2code/Tutorials/blob/develop/incompressible_flow/Inc_Laminar_Flat_Plate/lam_flatplate.cfg

Please explain the reason behind your requested changes and I will be more than happy to apply them!

2023-07-16 18:36 UTC, pcarruscag commented
The lists of possible options in those comments have become obsolete, we want to document options in a single place (config_template) and only note what is important for particular cases.

2023-07-16 18:38 UTC, pcarruscag commented
For example these 2 configs are copy pasted from the quick start and only a couple lines are different.

2023-07-16 18:41 UTC, pcarruscag commented
And since they are not used for any test I would even say it would be more valuable to simply instruct what few options need to change in the tutorial, and avoid adding these files which will become outdated (note that I did ask for those tests)

2023-07-20 20:08 UTC, frx-wintermute commented
> The lists of possible options in those comments have become obsolete, we want to document options in a single place (config_template) and only note what is important for particular cases.

I have stripped out all the comments from the two config files.

2023-07-21 02:44 UTC, pcarruscag approved these changes
Thank you

2023-07-21 02:44 UTC, merged